# Generated by Django 5.1.5 on 2025-02-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='calendly_link',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='provider_images/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='portfolio_link',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='theme',
            field=models.TextField(blank=True, default='No specific theme'),
        ),
    ]
